# Generated by Django 3.1.1 on 2021-04-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_country',
            new_name='company_wage',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_size',
        ),
    ]
